fix ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,12 +34,12 @@ jobs:
       - name: Install Poetry (Unix)
         if: runner.os != 'Windows'
         run: |
-          curl -sSL https://install.python-poetry.org | python3 -
-
+          curl -sSL https://install.python-poetry.org | python3 - || echo "Poetry installation failed"
+      
       - name: Install Poetry (Windows)
         if: runner.os == 'Windows'
         run: |
-          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python -
+          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python - || echo "Poetry installation failed"
           echo "$HOME\AppData\Roaming\Python\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
         shell: pwsh
 
